# Generated by Django 5.0.1 on 2024-01-25 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_users_contactno_alter_users_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='contactNo',
            new_name='contact_no',
        ),
    ]
