# Generated by Django 5.0.1 on 2024-01-25 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_users_dob'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='contact_no',
            new_name='contactNo',
        ),
    ]
