# Generated by Django 5.0.1 on 2024-01-27 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_rename_contact_no_users_contactno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='contactNo',
            field=models.CharField(max_length=10),
        ),
    ]
