# Generated by Django 5.0.1 on 2024-01-31 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0004_alter_orders_date_alter_orders_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmed', models.BooleanField(default=False)),
                ('dispatched', models.BooleanField(default=False)),
                ('shipped', models.BooleanField(default=False)),
                ('in_transit', models.BooleanField(default=False)),
                ('out_for_delivery', models.BooleanField(default=False)),
                ('final_status', models.CharField(max_length=100)),
                ('orderId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.orders')),
            ],
        ),
    ]
