# Generated by Django 5.0.1 on 2024-02-01 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderTrack', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordertrack',
            name='confirmed',
            field=models.JSONField(blank=True, default=models.BooleanField(default=False)),
        ),
        migrations.AlterField(
            model_name='ordertrack',
            name='dispatched',
            field=models.JSONField(blank=True, default=models.BooleanField(default=False)),
        ),
        migrations.AlterField(
            model_name='ordertrack',
            name='final_status',
            field=models.CharField(default='pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='ordertrack',
            name='in_transit',
            field=models.JSONField(blank=True, default=models.BooleanField(default=False)),
        ),
        migrations.AlterField(
            model_name='ordertrack',
            name='out_for_delivery',
            field=models.JSONField(blank=True, default=models.BooleanField(default=False)),
        ),
        migrations.AlterField(
            model_name='ordertrack',
            name='shipped',
            field=models.JSONField(blank=True, default=models.BooleanField(default=False)),
        ),
    ]
