# Generated by Django 5.0.1 on 2024-01-23 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('cancled', 'Cancled'), ('delivered', 'Delivered')], max_length=100),
        ),
    ]
